name: Example Runner Cleanup Usage

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run mathio/gha-cleanup action
        uses: mathio/gha-cleanup@v1
        with:
          remove-browsers: true
          verbose: true
